// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACdJpLxg993E910a_BGM_5OlcmQsOZ0ts',
    appId: '1:446389074827:web:ba146aa5a780ddafb6cd8e',
    messagingSenderId: '446389074827',
    projectId: 'gupsup-be6b7',
    authDomain: 'gupsup-be6b7.firebaseapp.com',
    storageBucket: 'gupsup-be6b7.appspot.com',
    measurementId: 'G-MZ1XJ7YSQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHc3LqR0rY6LlFZq_X90Gs5tENMBZRj1I',
    appId: '1:446389074827:android:cf6c0250b4072532b6cd8e',
    messagingSenderId: '446389074827',
    projectId: 'gupsup-be6b7',
    storageBucket: 'gupsup-be6b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWuf2_FeFf3o9SCK-8UBD1l0Z4eePUZ5w',
    appId: '1:446389074827:ios:844e6f1203b0ed4db6cd8e',
    messagingSenderId: '446389074827',
    projectId: 'gupsup-be6b7',
    storageBucket: 'gupsup-be6b7.appspot.com',
    iosBundleId: 'com.example.gupsup',
  );

}